# Generated by Django 3.2.23 on 2023-12-11 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('body', models.TextField()),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('pending_approval', models.BooleanField(default=False)),
                ('date_submitted', models.DateTimeField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('failed_approval', models.BooleanField(default=False)),
                ('date_failed', models.DateTimeField(blank=True, null=True)),
                ('reason_failed', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_approved'],
            },
        ),
    ]
