# Generated by Django 3.2.23 on 2023-12-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
